### ISSUE TITLE
Roadmap to 1.5.0

### ISSUE THREAD

**Issue by kangax** [kangax/fabric.js#1830]
- [x] try to fit line coordinate issue in, control box need a fix.
- [x] Investigate performance impact and other issue of #1773
- [x] Update documentation on how originX/Y works in groups.
- [x] Check if ie8 with excanvas can render test without cufon, then drop cufon
- [x] Fix toSvg export for Itext
- [x] fix page jump for itext editing when page is scrolled.
- [x] fix #1808 
- [x] iText 2.0 improvements.
- [ ] document all the features inserted ON-THE-FLY
